[versions]
android-gradle = "8.2.0"
androidx-annotation = "1.7.0"
androidx-appCompat = "1.6.1"
androidx-cardView = "1.0.0"
androidx-legacySupport = "1.0.0"
androidx-percentLayout = "1.0.0"
androidx-recyclerView = "1.3.2"
androidx-preference = "1.2.1"
androidx-lifecycle = "2.6.2"
crashlytics = "2.10.1@aar"
dagger-hilt = "2.49"
fabricGradle = "1.31.2"
kotlin = "1.8.22"
kotlinova = "3.0.0-alpha20"
google-material = "1.10.0"
google-wearableLibrary = "2.9.0"
google-playServices-wearable = "18.1.0"
licensesDialog = "2.2.0"
versionsGradle = "0.50.0"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-cardView = { module = "androidx.cardview:cardview", version.ref = "androidx-cardView" }
androidx-legacySupport = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacySupport" }
androidx-percentLayout = { module = "androidx.percentlayout:percentlayout", version.ref = "androidx-percentLayout" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerView" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
dagger-hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger-hilt" }
dagger-hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-wearableSupport = { module = "com.google.android.support:wearable", version.ref = "google.wearableLibrary" }
google-wearableLibrary = { module = "com.google.android.wearable:wearable", version.ref = "google-wearableLibrary" }
google-playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "google-playServices-wearable" }
kotlinova-core = { module = "si.inova.kotlinova:core", version.ref = "kotlinova" }
kotlinova-gradle = { module = "si.inova.kotlinova:gradle", version.ref = "kotlinova" }
crashlytics = { module = "com.crashlytics.sdk.android:crashlytics", version.ref = "crashlytics" }
fabricGradle = { module = "io.fabric.tools:gradle", version.ref = "fabricGradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
licensesDialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesDialog" }
versionsGradle = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsGradle" }
